# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ 
	"amdgpu"        
	"vfio_pci"
        "vfio"
        "vfio_iommu_type1"
        "vfio_virqfd"
  ];
  boot.kernelModules = [ "kvm-amd" "vfio" "vfio_iommu_type1" "vfio_pci" "vfio_virqfd" ];
  boot.kernelParams = ["iommu=pt" "iommu=1" "amd_iommu=on" "amdgpu.ppfeaturemask=0xffffffff" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = "options vfio-pci ids=10de:2208,10de:1aef";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2b04b975-6c4b-4ada-8553-2b5115a87bb9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2C9E-2099";
      fsType = "vfat";
    };

  fileSystems."/home/ruxy/virtual/drives" =
    { device = "/dev/disk/by-uuid/62b8463a-7fa1-4353-8847-07411d0bf866";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d8c66226-9ac8-4ac1-8a16-f7fbdc3a8873"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
  hardware.pulseaudio.enable = true;
}
